name: HiFi-C
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - k8=1.2=he8db53b_6
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - ld_impl_linux-64=2.44=h1423503_1
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgomp=15.1.0=h767d61c_4
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libzlib=1.3.1=hb9d3cd8_2
  - minimap2=2.30=h577a1d6_0
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.2=h26f9b46_0
  - parallel=20250822=ha770c72_0
  - perl=5.20.3.1=1
  - pigz=2.8=hadc24fc_1
  - pip=22.1.2=pyhd8ed1ab_0
  - python=3.7.12=hf930737_100_cpython
  - python_abi=3.7=4_cp37m
  - readline=8.2=h8c095d6_2
  - setuptools=65.3.0=py37h89c1867_0
  - sqlite=3.50.4=hbc0de68_0
  - sysroot_linux-64=2.34=he3f20f0_2
  - tk=8.6.13=noxft_hd72426e_102
  - tzdata=2025b=h78e105d_0
  - wheel=0.41.3=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2

